trabajo3/project/config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

trabajo3/project/core/urls.py
from django.contrib import admin
from django.urls import path
from core import views

app_name='core'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('producto/', views.producto, name='consultar'),
    path('guardar/', views.guardar, name='guardar'),
    path('eliminar/<int:id>', views.eliminar, name='eliminar'),
    #muestra el producto
    path('detalle/<int:id>', views.detalle, name='detalle'),
    #actualiza el producto
    path('editar/<int:id>', views.editar, name='editar'),
]

trabajo3/project/core/models.py
from django.db import models
from django import forms

# Create your models here.
class Producto(models.Model):
    nombre = models.CharField(max_length=30)
    precio = models.IntegerField()
    descripcion = models.CharField(max_length=100)
    
    def __str__(self):
        return f"{self.nombre} - $ {self.precio} -  {self.descripcion}"
    

trabajo3/project/core/views.py
from django.shortcuts import render, redirect
from .models import Producto
from django.contrib import messages


# Create your views here.
def index(request):
    return render(request, 'core/index.html')

def consultar(request): 
    productos = Producto.objects.all()
    return render(request, 'core/consultar.html', {
        'productos': productos
        })

def producto(request):
    productos = Producto.objects.all()
    return render(request, 'core/producto.html', {
        'productos': productos
        })


def guardar(request):
    #name en producto.html
    nombre = request.POST['nombre']
    precio = request.POST['precio']
    descripcion = request.POST['descripcion']
   #nueva variable = Modelo(izquierda, nombre en models.variable a la que hacemos referencia)
    p = Producto(nombre=nombre, precio=precio, descripcion=descripcion)
    #guardar datos
    p.save()
    messages.success(request, 'Producto guardado correctamente')
     #redireccionar a otra pagina
    return redirect('core:consultar')

def eliminar(request, id):
    p = Producto.objects.filter(pk=id)
    p.delete()
    messages.success(request, 'Producto eliminado correctamente')
    return redirect('core:consultar')

def detalle(request, id):
    producto = Producto.objects.get(pk=id)
    return render(request, 'core/productoEditar.html', {
        'producto' : producto
    })

def editar(request, id):
    nombre = request.POST['nombre']
    precio = request.POST['precio']
    descripcion = request.POST['descripcion']
    id = request.POST['id']
    Producto.objects.filter(pk=id).update(id=id, nombre=nombre,
                                               precio=precio,
                                                 descripcion=descripcion)
    messages.success(request, 'Producto actualizado correctamente')
    return redirect('core:consultar')

def buscar(request):
   pass

trabajo3/project/core/templates/core/index.html
{% extends 'core/padre.html' %}


{% block content %}

<h1 class="text-center">INDEX</h1>
{% endblock content %}

trabajo3/project/core/templates/core/padre.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'core:index' %}">INICIO</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link active" aria-current="page" href="{% url 'core:consultar' %}">PRODUCTO</a>
              <a class="nav-link" href="#">...</a>
              <a class="nav-link" href="#">...</a>
            </div>
          </div>
        </div>
      </nav>
      {% block content %}
        
      {% endblock content %}
</body>
</html>

trabajo3/project/core/templates/core/producto.html
{% extends 'core/padre.html' %}


{% block content %}
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success">{{ message }}</div>
    {% endfor %}
{% endif %}

<h3 class="text-center">PRODUCTOS </h3>

<form class="w-50 shadow mx-auto p-4 m-3 text-center" method="post" action="{% url 'core:guardar' %}">

    {% csrf_token %}

    Nombre:<input type="text" name="nombre" class="form-control my-2" required>

    Descripcion: <textarea name="descripcion" class="form-control my-2" cols="30" rows="5"></textarea>

    Precio:<input type="number" name="precio" class="form-control my-2" required>

    <input type="submit" value="Guardar" class="btn btn-primary">
</form>

<table class="table table-info w-75 mx-auto">
    <tr class="table table-dark">
        <th>Nombre</th>
        <th>Descripcion</th>
        <th>Precio</th>
        <th colspan="2"></th>
    </tr>
    {% for producto in productos %}
    <tr>
        <td>{{producto.nombre}}</td>
        <td>{{producto.descripcion}}</td>
        <td>{{producto.precio}}</td>
        <td>
            <form action="{% url 'core:eliminar' producto.id %}" method="post">
                {% csrf_token %}
                <button class="btn btn-danger" onclick="return confirm('Eliminar el producto seleccionado?')">
                    Eliminar
                </button>
            </form>
        </td>
        <td>
            <form action="{% url 'core:detalle' producto.id %}" method="post">
                {% csrf_token %}
                <button class="btn btn-warning" >
                    Modicar
                </button>
            </form>
        </td>
    </tr>
    {% endfor %}

</table>
{% endblock content %}

trabajo3/project/core/templates/core/productoEditar.html
{% extends 'core/padre.html' %}


{% block content %}

<h3 class="text-center">EDITAR PRODUCTO </h3>

<form class="w-50 shadow mx-auto p-4 m-3 text-center" method="post" action="{% url 'core:editar' producto.id %}">
    {% csrf_token %}

    <input type="hidden" name="id" value="{{producto.id}}">

    Nombre:<input type="text" name="nombre" class="form-control my-2" required value="{{producto.nombre}}">

    Descripcion: <textarea name="descripcion" class="form-control my-2" cols="30" rows="5"> {{producto.descripcion}}</textarea>

    Precio:<input type="number" name="precio" class="form-control my-2" required value="{{producto.precio}}">

    <input type="submit" value="Actualizar" class="btn btn-warning">
</form>


{% endblock content %}